parameters:
    app.crawl_sleep: 1

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\EventListener\CrawlerListener:
        tags:
            - { name: kernel.event_listener, event: app.crawler.crawl, method: 'onCrawlEvent' }

    App\Crawler\ResponseParser:
        arguments:
            $eventDispatcher: '@event_dispatcher'

    App\Services\CrawlerService:
        arguments:
            - '@App\Services\ResponseRetrieverService'
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@workflow.registry'
            - '%app.crawl_sleep%'
